version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:13-jdk-buster

    working_directory: ~/ash

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle build
      - run: gradle test
